### PR TITLE
Change client_public_key from requestor to provider in SubtaskResultsVerify message

### PR DESCRIPTION
**Pull request by kbeker**
Fix related with public keys in SubtaskResultsVerify use case

### CODE REVIEW

**Review by Jakub89 — CHANGES_REQUESTED** [review]
test

**Review by Jakub89 — APPROVED** [review]

**Review by Jakub89 — APPROVED** [review]

**Comment by rwrzesien** [comment]
@kbeker What about the tests ? I remember that they were also defining usage of provider/requestor key.

**Review by rwrzesien — APPROVED** [review]

**Comment by kbeker** [comment]
@rwrzesien But in this PR I have also changed these keys in tests :) Or you had on your mind different tests?

**Review by dybi — APPROVED** [review]

**Comment by rwrzesien** [comment]
@kbeker I thought I have dropped this message before posting, I must have misclicked, sorry for confusion.

**Pull request merged**
